"use client"

import { useContext } from "react"
import { Context } from "@/context/ContextProvider"
import { getStringWithTime } from "@/helpers/getStringWithTime"




export function Head () {

    const { state } = useContext(Context)

    return(
        <head>
            <title>{getStringWithTime(state.seconds)}</title>
            <meta name="description" content="Generated by create next app"></meta>
            <link 
                rel="shortcut icon"
                href={state.curr % 2 ? "/break-icon.svg" : "/pomodoro-icon.svg"}
                type="image/x-icon"
            />
        </head>
    )
}